name = "Rewriters"
uuid = "1df27592-1edd-4a6d-9e16-9f1b005f54b8"
authors = ["Alessandro <none>"]
version = "0.1.0"

[deps]
TermInterface = "8ea1fca8-c5ef-4a55-8b96-4e9afe9c9a3c"

[compat]
TermInterface = "0.1.5"